export const COUNTRY_LOCATION_OPTIONS = [
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Egypt",
  "Jordan",
  "Turkey",
  "Morocco",
  "South Africa",
  "United Kingdom",
  "Germany",
  "France",
  "Netherlands",
  "Italy",
  "Spain",
  "United States",
  "Canada",
  "Singapore",
  "Australia",
];

export const REGION_LOCATION_OPTIONS = [
  "Middle East",
  "Europe",
  "North America",
  "Africa",
  "Asia-Pacific",
  "Global",
];

export const locationZoneMap = {
  India: "india",
  "United Arab Emirates": "gcc",
  "Saudi Arabia": "gcc",
  Qatar: "gcc",
  Kuwait: "gcc",
  Bahrain: "gcc",
  Oman: "gcc",
  Egypt: "mena",
  Jordan: "mena",
  Turkey: "mena",
  Morocco: "mena",
  "South Africa": "africa",
  "United Kingdom": "europe",
  Germany: "europe",
  France: "europe",
  Netherlands: "europe",
  Italy: "europe",
  Spain: "europe",
  "United States": "north_america",
  Canada: "north_america",
  Singapore: "apac",
  Australia: "apac",
  "Middle East": "gcc",
  Europe: "europe",
  "North America": "north_america",
  Africa: "africa",
  "Asia-Pacific": "apac",
  Global: "global",
};
